name: Kyi Myo Han

on:
  push:
    branches: "v[0-9]+.[0-9]+"                      
               
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: incremental release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install railway app
        run: npm i -g @railway/cli

      - name: deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.KMH_RAIL_TOKEN }}

      - name: Send message to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA55 CI/CD Assignment Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:*\nKyi Myo Han"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:*\nA0265093B"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Email:*\nkyimyohanvov@gmail.com"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repositoryUrl }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment:*\n${{ secrets.KMH_GO_FORTUEN_WEBSITE_URL }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ secrets.KMH_GO_FORTUEN_WEBSITE_URL }}/|Open Application>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MY_SLACK_CHANNEL_FOR_TESTING }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        